diff.astextplain.textconv=astextplain
filter.lfs.clean=git-lfs clean -- %f
filter.lfs.smudge=git-lfs smudge -- %f
filter.lfs.process=git-lfs filter-process
filter.lfs.required=true
http.sslbackend=openssl
http.sslcainfo=C:/Program Files/Git/mingw64/ssl/certs/ca-bundle.crt
core.autocrlf=true
core.fscache=true
core.symlinks=false
core.usebuiltinfsmonitor=true
pull.rebase=false
init.defaultbranch=master
gui.recentrepo=E:/github/Git-Course
gui.recentrepo=E:/order-summary-component-main/challenge/order-summary
credential.helperselector.selected=<
core.editor=brackets -w
core.editot=brackets
user.name='mohamed-alex'
user.email='mohamed_el_sayed@hotmail.com'
alias.st=status
core.repositoryformatversion=0
core.filemode=false
core.bare=false
core.logallrefupdates=true
core.symlinks=false
core.ignorecase=true
remote.origin.url=https://github.com/mohamed-alex/MultiplicationTableGame.git
remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*
